### ISSUE TITLE
Margin/footer issue on mobile

### ISSUE THREAD

**Issue by pale-bluedot** [opera7133/tella#152]
Hi,

Is there some configuration that needs to be done for my Hugo website to display properly on mobile? I've noticed the margins are large and the footer content overflows to the right of the screen. Any suggestions appreciated!

![Screenshot_20240821-120212](https://github.com/user-attachments/assets/45fb5818-218d-4f22-bc50-119af11887c9)

**Comment by xopino** [comment]
This typically occur when one element is wider than the rest of the page or its container. It can also be caused by margins being applyied improperly.-
 
 I can see from the picture some elements on the right (the links and the Go Up button). Did you try to remove that elements to check if they are causing this behaviour?
 
 I recommend you to use the inspector on your browser, and try to find the element causing this, once you get the element, start disabling some css attributes to see which one is the cause.
